// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_rules.sql

package repository

import (
	"context"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (device_id, metric, operator, threshold, is_enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING id, device_id, metric, operator, threshold, is_enabled, created_at, updated_at, deleted_at
`

type CreateAlertRuleParams struct {
	DeviceID  int64   `json:"device_id"`
	Metric    string  `json:"metric"`
	Operator  string  `json:"operator"`
	Threshold float64 `json:"threshold"`
	IsEnabled bool    `json:"is_enabled"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, createAlertRule,
		arg.DeviceID,
		arg.Metric,
		arg.Operator,
		arg.Threshold,
		arg.IsEnabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Metric,
		&i.Operator,
		&i.Threshold,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, device_id, metric, operator, threshold, is_enabled, created_at, updated_at, deleted_at FROM alert_rules
 WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAlertRule(ctx context.Context, id int64) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, getAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Metric,
		&i.Operator,
		&i.Threshold,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAlertRulesByDevice = `-- name: ListAlertRulesByDevice :many
SELECT id, device_id, metric, operator, threshold, is_enabled, created_at, updated_at, deleted_at FROM alert_rules
 WHERE device_id = ? AND deleted_at IS NULL
 ORDER BY created_at ASC
`

func (q *Queries) ListAlertRulesByDevice(ctx context.Context, deviceID int64) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRulesByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Metric,
			&i.Operator,
			&i.Threshold,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRulesByDevice = `-- name: ListEnabledAlertRulesByDevice :many
SELECT id, device_id, metric, operator, threshold, is_enabled, created_at, updated_at, deleted_at FROM alert_rules
 WHERE device_id  = ?
   AND is_enabled = TRUE
   AND deleted_at IS NULL
`

func (q *Queries) ListEnabledAlertRulesByDevice(ctx context.Context, deviceID int64) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAlertRulesByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Metric,
			&i.Operator,
			&i.Threshold,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAlertRule = `-- name: SoftDeleteAlertRule :exec
UPDATE alert_rules
   SET deleted_at = datetime('now'),
       updated_at = datetime('now')
 WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAlertRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteAlertRule, id)
	return err
}

const toggleAlertRule = `-- name: ToggleAlertRule :one
UPDATE alert_rules
   SET is_enabled = NOT is_enabled,
       updated_at = datetime('now')
 WHERE id = ? AND deleted_at IS NULL
RETURNING id, device_id, metric, operator, threshold, is_enabled, created_at, updated_at, deleted_at
`

func (q *Queries) ToggleAlertRule(ctx context.Context, id int64) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, toggleAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Metric,
		&i.Operator,
		&i.Threshold,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
   SET metric     = ?,
       operator   = ?,
       threshold  = ?,
       is_enabled = ?,
       updated_at = datetime('now')
 WHERE id = ? AND deleted_at IS NULL
RETURNING id, device_id, metric, operator, threshold, is_enabled, created_at, updated_at, deleted_at
`

type UpdateAlertRuleParams struct {
	Metric    string  `json:"metric"`
	Operator  string  `json:"operator"`
	Threshold float64 `json:"threshold"`
	IsEnabled bool    `json:"is_enabled"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, updateAlertRule,
		arg.Metric,
		arg.Operator,
		arg.Threshold,
		arg.IsEnabled,
		arg.ID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Metric,
		&i.Operator,
		&i.Threshold,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
