// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package repository

import (
	"context"
	"encoding/json"
	"time"
)

const createDeviceToken = `-- name: CreateDeviceToken :one
INSERT INTO device_tokens (user_id, name, token_hash, abilities, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, abilities, last_used_at, expires_at, created_at, updated_at
`

type CreateDeviceTokenParams struct {
	UserID    int64           `json:"user_id"`
	Name      string          `json:"name"`
	TokenHash string          `json:"token_hash"`
	Abilities json.RawMessage `json:"abilities"`
	ExpiresAt *time.Time      `json:"expires_at"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, createDeviceToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Abilities,
		arg.ExpiresAt,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Abilities,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE id = ?
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, id)
	return err
}

const getDeviceTokenByHash = `-- name: GetDeviceTokenByHash :one
SELECT id, user_id, name, token_hash, abilities, last_used_at, expires_at, created_at, updated_at FROM device_tokens
 WHERE token_hash = ?
   AND (expires_at IS NULL OR expires_at > datetime('now'))
`

func (q *Queries) GetDeviceTokenByHash(ctx context.Context, tokenHash string) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, getDeviceTokenByHash, tokenHash)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Abilities,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, name, abilities, last_used_at, expires_at, created_at
  FROM device_tokens
 WHERE user_id = ?
 ORDER BY created_at DESC
`

type ListDeviceTokensByUserRow struct {
	ID         int64           `json:"id"`
	UserID     int64           `json:"user_id"`
	Name       string          `json:"name"`
	Abilities  json.RawMessage `json:"abilities"`
	LastUsedAt *time.Time      `json:"last_used_at"`
	ExpiresAt  *time.Time      `json:"expires_at"`
	CreatedAt  time.Time       `json:"created_at"`
}

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID int64) ([]ListDeviceTokensByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeviceTokensByUserRow
	for rows.Next() {
		var i ListDeviceTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Abilities,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceTokenLastUsed = `-- name: UpdateDeviceTokenLastUsed :exec
UPDATE device_tokens
   SET last_used_at = datetime('now'),
       updated_at   = datetime('now')
 WHERE id = ?
`

func (q *Queries) UpdateDeviceTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDeviceTokenLastUsed, id)
	return err
}
