// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceToken = `-- name: CreateDeviceToken :one
INSERT INTO device_tokens (user_id, name, token_hash, abilities, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, abilities, last_used_at, expires_at, created_at, updated_at
`

type CreateDeviceTokenParams struct {
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	Abilities []byte             `json:"abilities"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, createDeviceToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Abilities,
		arg.ExpiresAt,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Abilities,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE id = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, id)
	return err
}

const getDeviceTokenByHash = `-- name: GetDeviceTokenByHash :one
SELECT id, user_id, name, token_hash, abilities, last_used_at, expires_at, created_at, updated_at FROM device_tokens
 WHERE token_hash = $1
   AND (expires_at IS NULL OR expires_at > NOW())
`

// デバイスからの Bearer リクエスト受信時に token_hash で検索し認証に使用
func (q *Queries) GetDeviceTokenByHash(ctx context.Context, tokenHash string) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByHash, tokenHash)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Abilities,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, name, abilities, last_used_at, expires_at, created_at
  FROM device_tokens
 WHERE user_id = $1
 ORDER BY created_at DESC
`

type ListDeviceTokensByUserRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	Abilities  []byte             `json:"abilities"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID int64) ([]ListDeviceTokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeviceTokensByUserRow
	for rows.Next() {
		var i ListDeviceTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Abilities,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceTokenLastUsed = `-- name: UpdateDeviceTokenLastUsed :exec
UPDATE device_tokens
   SET last_used_at = NOW(),
       updated_at   = NOW()
 WHERE id = $1
`

func (q *Queries) UpdateDeviceTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateDeviceTokenLastUsed, id)
	return err
}
