// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package repository

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, mac_address, location, is_active)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at
`

type CreateDeviceParams struct {
	UserID     int64   `json:"user_id"`
	Name       string  `json:"name"`
	MacAddress string  `json:"mac_address"`
	Location   *string `json:"location"`
	IsActive   bool    `json:"is_active"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.UserID,
		arg.Name,
		arg.MacAddress,
		arg.Location,
		arg.IsActive,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at FROM devices
 WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByMacAddress = `-- name: GetDeviceByMacAddress :one
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at FROM devices
 WHERE mac_address = ? AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByMacAddress(ctx context.Context, macAddress string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByMacAddress, macAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at FROM devices
 WHERE user_id = ? AND deleted_at IS NULL
 ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID int64) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.MacAddress,
			&i.Location,
			&i.IsActive,
			&i.LastCommunicatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices
   SET deleted_at = datetime('now'),
       updated_at = datetime('now')
 WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteDevice, id)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
   SET name        = ?,
       mac_address = ?,
       location    = ?,
       is_active   = ?,
       updated_at  = datetime('now')
 WHERE id = ? AND deleted_at IS NULL
RETURNING id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at
`

type UpdateDeviceParams struct {
	Name       string  `json:"name"`
	MacAddress string  `json:"mac_address"`
	Location   *string `json:"location"`
	IsActive   bool    `json:"is_active"`
	ID         int64   `json:"id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevice,
		arg.Name,
		arg.MacAddress,
		arg.Location,
		arg.IsActive,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDeviceLastCommunicated = `-- name: UpdateDeviceLastCommunicated :exec
UPDATE devices
   SET last_communicated_at = datetime('now'),
       updated_at           = datetime('now')
 WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) UpdateDeviceLastCommunicated(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDeviceLastCommunicated, id)
	return err
}
