// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, mac_address, location, is_active, locality, crop, planting_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at, locality, crop, planting_date
`

type CreateDeviceParams struct {
	UserID       int64       `json:"user_id"`
	Name         string      `json:"name"`
	MacAddress   string      `json:"mac_address"`
	Location     *string     `json:"location"`
	IsActive     bool        `json:"is_active"`
	Locality     *string     `json:"locality"`
	Crop         *string     `json:"crop"`
	PlantingDate pgtype.Date `json:"planting_date"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Name,
		arg.MacAddress,
		arg.Location,
		arg.IsActive,
		arg.Locality,
		arg.Crop,
		arg.PlantingDate,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Locality,
		&i.Crop,
		&i.PlantingDate,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at, locality, crop, planting_date FROM devices
 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Locality,
		&i.Crop,
		&i.PlantingDate,
	)
	return i, err
}

const getDeviceByMacAddress = `-- name: GetDeviceByMacAddress :one
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at, locality, crop, planting_date FROM devices
 WHERE mac_address = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByMacAddress(ctx context.Context, macAddress string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByMacAddress, macAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Locality,
		&i.Crop,
		&i.PlantingDate,
	)
	return i, err
}

const listAllDevices = `-- name: ListAllDevices :many
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at, locality, crop, planting_date FROM devices
 WHERE deleted_at IS NULL
 ORDER BY id
`

// 全ユーザー横断で有効なデバイスを列挙する (所在地 backfill 専用)。
func (q *Queries) ListAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.MacAddress,
			&i.Location,
			&i.IsActive,
			&i.LastCommunicatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Locality,
			&i.Crop,
			&i.PlantingDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at, locality, crop, planting_date FROM devices
 WHERE user_id = $1 AND deleted_at IS NULL
 ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID int64) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.MacAddress,
			&i.Location,
			&i.IsActive,
			&i.LastCommunicatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Locality,
			&i.Crop,
			&i.PlantingDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices
   SET deleted_at = NOW(),
       updated_at = NOW()
 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDevice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, id)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
   SET name          = $2,
       mac_address   = $3,
       location      = $4,
       is_active     = $5,
       locality      = $6,
       crop          = $7,
       planting_date = $8,
       updated_at    = NOW()
 WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, mac_address, location, is_active, last_communicated_at, created_at, updated_at, deleted_at, locality, crop, planting_date
`

type UpdateDeviceParams struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	MacAddress   string      `json:"mac_address"`
	Location     *string     `json:"location"`
	IsActive     bool        `json:"is_active"`
	Locality     *string     `json:"locality"`
	Crop         *string     `json:"crop"`
	PlantingDate pgtype.Date `json:"planting_date"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.MacAddress,
		arg.Location,
		arg.IsActive,
		arg.Locality,
		arg.Crop,
		arg.PlantingDate,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MacAddress,
		&i.Location,
		&i.IsActive,
		&i.LastCommunicatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Locality,
		&i.Crop,
		&i.PlantingDate,
	)
	return i, err
}

const updateDeviceLastCommunicated = `-- name: UpdateDeviceLastCommunicated :exec
UPDATE devices
   SET last_communicated_at = NOW(),
       updated_at           = NOW()
 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateDeviceLastCommunicated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateDeviceLastCommunicated, id)
	return err
}

const updateDeviceLocality = `-- name: UpdateDeviceLocality :exec
UPDATE devices
   SET locality   = $2,
       updated_at = NOW()
 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateDeviceLocalityParams struct {
	ID       int64   `json:"id"`
	Locality *string `json:"locality"`
}

// locality 列のみを更新する (backfill 用・他フィールドと location は不変)。
func (q *Queries) UpdateDeviceLocality(ctx context.Context, arg UpdateDeviceLocalityParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLocality, arg.ID, arg.Locality)
	return err
}
