// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"
	"time"
)

type AlertHistory struct {
	ID          int64      `json:"id"`
	AlertRuleID int64      `json:"alert_rule_id"`
	Metric      string     `json:"metric"`
	Operator    string     `json:"operator"`
	Threshold   float64    `json:"threshold"`
	ActualValue float64    `json:"actual_value"`
	IsNotified  bool       `json:"is_notified"`
	TriggeredAt time.Time  `json:"triggered_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type AlertRule struct {
	ID        int64      `json:"id"`
	DeviceID  int64      `json:"device_id"`
	Metric    string     `json:"metric"`
	Operator  string     `json:"operator"`
	Threshold float64    `json:"threshold"`
	IsEnabled bool       `json:"is_enabled"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Device struct {
	ID                 int64      `json:"id"`
	UserID             int64      `json:"user_id"`
	Name               string     `json:"name"`
	MacAddress         string     `json:"mac_address"`
	Location           *string    `json:"location"`
	IsActive           bool       `json:"is_active"`
	LastCommunicatedAt *time.Time `json:"last_communicated_at"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	DeletedAt          *time.Time `json:"deleted_at"`
}

type DeviceToken struct {
	ID         int64           `json:"id"`
	UserID     int64           `json:"user_id"`
	Name       string          `json:"name"`
	TokenHash  string          `json:"token_hash"`
	Abilities  json.RawMessage `json:"abilities"`
	LastUsedAt *time.Time      `json:"last_used_at"`
	ExpiresAt  *time.Time      `json:"expires_at"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type SensorReading struct {
	ID          int64      `json:"id"`
	DeviceID    int64      `json:"device_id"`
	Temperature float64    `json:"temperature"`
	Humidity    float64    `json:"humidity"`
	RecordedAt  time.Time  `json:"recorded_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type User struct {
	ID              int64      `json:"id"`
	Name            string     `json:"name"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}
