// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CountAlertHistoriesInRange(ctx context.Context, arg CountAlertHistoriesInRangeParams) (int64, error)
	CountSensorReadingsInRange(ctx context.Context, arg CountSensorReadingsInRangeParams) (int64, error)
	CreateAlertHistory(ctx context.Context, arg CreateAlertHistoryParams) (AlertHistory, error)
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error)
	CreateSensorReading(ctx context.Context, arg CreateSensorReadingParams) (SensorReading, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeviceToken(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAlertRule(ctx context.Context, id int64) (AlertRule, error)
	GetDevice(ctx context.Context, id int64) (Device, error)
	GetDeviceByMacAddress(ctx context.Context, macAddress string) (Device, error)
	GetDeviceTokenByHash(ctx context.Context, tokenHash string) (DeviceToken, error)
	GetLatestSensorReading(ctx context.Context, deviceID int64) (SensorReading, error)
	GetSensorReadingsSummary(ctx context.Context, arg GetSensorReadingsSummaryParams) (GetSensorReadingsSummaryRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAlertHistoriesPaginated(ctx context.Context, arg ListAlertHistoriesPaginatedParams) ([]ListAlertHistoriesPaginatedRow, error)
	ListAlertRulesByDevice(ctx context.Context, deviceID int64) ([]AlertRule, error)
	ListDailySensorAggregates(ctx context.Context, arg ListDailySensorAggregatesParams) ([]ListDailySensorAggregatesRow, error)
	ListDeviceTokensByUser(ctx context.Context, userID int64) ([]ListDeviceTokensByUserRow, error)
	ListDevicesByUser(ctx context.Context, userID int64) ([]Device, error)
	ListEnabledAlertRulesByDevice(ctx context.Context, deviceID int64) ([]AlertRule, error)
	ListLatestSensorReadings(ctx context.Context, deviceID int64) ([]SensorReading, error)
	ListRecentSensorReadings(ctx context.Context, arg ListRecentSensorReadingsParams) ([]SensorReading, error)
	ListSensorReadingsPaginated(ctx context.Context, arg ListSensorReadingsPaginatedParams) ([]SensorReading, error)
	ListUnnotifiedAlertHistoriesWithDevice(ctx context.Context, arg ListUnnotifiedAlertHistoriesWithDeviceParams) ([]ListUnnotifiedAlertHistoriesWithDeviceRow, error)
	MarkAlertHistoryNotified(ctx context.Context, id int64) error
	MarkUserEmailVerified(ctx context.Context, id int64) error
	SoftDeleteAlertRule(ctx context.Context, id int64) error
	SoftDeleteDevice(ctx context.Context, id int64) error
	ToggleAlertRule(ctx context.Context, id int64) (AlertRule, error)
	UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	UpdateDeviceLastCommunicated(ctx context.Context, id int64) error
	UpdateDeviceTokenLastUsed(ctx context.Context, id int64) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
