// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor_readings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSensorReadingsInRange = `-- name: CountSensorReadingsInRange :one
SELECT COUNT(*)::BIGINT AS total
  FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at BETWEEN $2 AND $3
   AND deleted_at IS NULL
`

type CountSensorReadingsInRangeParams struct {
	DeviceID     int64              `json:"device_id"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
	RecordedAt_2 pgtype.Timestamptz `json:"recorded_at_2"`
}

func (q *Queries) CountSensorReadingsInRange(ctx context.Context, arg CountSensorReadingsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSensorReadingsInRange, arg.DeviceID, arg.RecordedAt, arg.RecordedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSensorReading = `-- name: CreateSensorReading :one
INSERT INTO sensor_readings (device_id, temperature, humidity, recorded_at)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at
`

type CreateSensorReadingParams struct {
	DeviceID    int64              `json:"device_id"`
	Temperature pgtype.Numeric     `json:"temperature"`
	Humidity    pgtype.Numeric     `json:"humidity"`
	RecordedAt  pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) CreateSensorReading(ctx context.Context, arg CreateSensorReadingParams) (SensorReading, error) {
	row := q.db.QueryRow(ctx, createSensorReading,
		arg.DeviceID,
		arg.Temperature,
		arg.Humidity,
		arg.RecordedAt,
	)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Temperature,
		&i.Humidity,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestSensorReading = `-- name: GetLatestSensorReading :one
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id = $1 AND deleted_at IS NULL
 ORDER BY recorded_at DESC
 LIMIT 1
`

// ダッシュボードでデバイスごとの最新値表示に使用
func (q *Queries) GetLatestSensorReading(ctx context.Context, deviceID int64) (SensorReading, error) {
	row := q.db.QueryRow(ctx, getLatestSensorReading, deviceID)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Temperature,
		&i.Humidity,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSensorReadingsSummary = `-- name: GetSensorReadingsSummary :one
SELECT
    AVG(temperature)::NUMERIC(5, 2) AS avg_temperature,
    MAX(temperature)                AS max_temperature,
    MIN(temperature)                AS min_temperature,
    AVG(humidity)::NUMERIC(5, 2)    AS avg_humidity,
    MAX(humidity)                   AS max_humidity,
    MIN(humidity)                   AS min_humidity,
    COUNT(*)::BIGINT                AS sample_count
  FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at BETWEEN $2 AND $3
   AND deleted_at IS NULL
`

type GetSensorReadingsSummaryParams struct {
	DeviceID     int64              `json:"device_id"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
	RecordedAt_2 pgtype.Timestamptz `json:"recorded_at_2"`
}

type GetSensorReadingsSummaryRow struct {
	AvgTemperature pgtype.Numeric `json:"avg_temperature"`
	MaxTemperature interface{}    `json:"max_temperature"`
	MinTemperature interface{}    `json:"min_temperature"`
	AvgHumidity    pgtype.Numeric `json:"avg_humidity"`
	MaxHumidity    interface{}    `json:"max_humidity"`
	MinHumidity    interface{}    `json:"min_humidity"`
	SampleCount    int64          `json:"sample_count"`
}

// センサーデータ履歴画面の集計ボックス用
func (q *Queries) GetSensorReadingsSummary(ctx context.Context, arg GetSensorReadingsSummaryParams) (GetSensorReadingsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSensorReadingsSummary, arg.DeviceID, arg.RecordedAt, arg.RecordedAt_2)
	var i GetSensorReadingsSummaryRow
	err := row.Scan(
		&i.AvgTemperature,
		&i.MaxTemperature,
		&i.MinTemperature,
		&i.AvgHumidity,
		&i.MaxHumidity,
		&i.MinHumidity,
		&i.SampleCount,
	)
	return i, err
}

const listDailySensorAggregates = `-- name: ListDailySensorAggregates :many
SELECT
    DATE(recorded_at)                       AS reading_date,
    AVG(temperature)::NUMERIC(5, 2)         AS avg_temperature,
    MAX(temperature)                        AS max_temperature,
    MIN(temperature)                        AS min_temperature,
    AVG(humidity)::NUMERIC(5, 2)            AS avg_humidity,
    MAX(humidity)                           AS max_humidity,
    MIN(humidity)                           AS min_humidity,
    COUNT(*)::BIGINT                        AS sample_count
  FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at >= $2
   AND deleted_at IS NULL
 GROUP BY DATE(recorded_at)
 ORDER BY DATE(recorded_at) ASC
`

type ListDailySensorAggregatesParams struct {
	DeviceID   int64              `json:"device_id"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

type ListDailySensorAggregatesRow struct {
	ReadingDate    pgtype.Date    `json:"reading_date"`
	AvgTemperature pgtype.Numeric `json:"avg_temperature"`
	MaxTemperature interface{}    `json:"max_temperature"`
	MinTemperature interface{}    `json:"min_temperature"`
	AvgHumidity    pgtype.Numeric `json:"avg_humidity"`
	MaxHumidity    interface{}    `json:"max_humidity"`
	MinHumidity    interface{}    `json:"min_humidity"`
	SampleCount    int64          `json:"sample_count"`
}

// 3日/7日/30日グラフ用: 日別の平均/最大/最小を集計 (24h以外の複数日はこの集計経路)
func (q *Queries) ListDailySensorAggregates(ctx context.Context, arg ListDailySensorAggregatesParams) ([]ListDailySensorAggregatesRow, error) {
	rows, err := q.db.Query(ctx, listDailySensorAggregates, arg.DeviceID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailySensorAggregatesRow
	for rows.Next() {
		var i ListDailySensorAggregatesRow
		if err := rows.Scan(
			&i.ReadingDate,
			&i.AvgTemperature,
			&i.MaxTemperature,
			&i.MinTemperature,
			&i.AvgHumidity,
			&i.MaxHumidity,
			&i.MinHumidity,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailySensorAggregatesJST = `-- name: ListDailySensorAggregatesJST :many
SELECT
    DATE(recorded_at AT TIME ZONE 'Asia/Tokyo') AS reading_date,
    AVG(temperature)::NUMERIC(5, 2)             AS avg_temperature,
    MAX(temperature)                            AS max_temperature,
    MIN(temperature)                            AS min_temperature,
    AVG(humidity)::NUMERIC(5, 2)                AS avg_humidity,
    MAX(humidity)                               AS max_humidity,
    MIN(humidity)                               AS min_humidity,
    COUNT(*)::BIGINT                            AS sample_count
  FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at >= $2
   AND deleted_at IS NULL
 GROUP BY DATE(recorded_at AT TIME ZONE 'Asia/Tokyo')
 ORDER BY DATE(recorded_at AT TIME ZONE 'Asia/Tokyo') ASC
`

type ListDailySensorAggregatesJSTParams struct {
	DeviceID   int64              `json:"device_id"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

type ListDailySensorAggregatesJSTRow struct {
	ReadingDate    pgtype.Date    `json:"reading_date"`
	AvgTemperature pgtype.Numeric `json:"avg_temperature"`
	MaxTemperature interface{}    `json:"max_temperature"`
	MinTemperature interface{}    `json:"min_temperature"`
	AvgHumidity    pgtype.Numeric `json:"avg_humidity"`
	MaxHumidity    interface{}    `json:"max_humidity"`
	MinHumidity    interface{}    `json:"min_humidity"`
	SampleCount    int64          `json:"sample_count"`
}

// 統計分析ページ(長期トレンド/季節サマリ)用: JST 暦日でバケットした日次集計。
// 月次/年次ロールアップは handler 境界で本クエリの日次行を二段集約する(月次ΔT=日次ΔTの平均)。
// 既存 ListDailySensorAggregates(DATE() の TZ 非明示=UTC バケット)は 3d/7d/30d グラフ用に無改変で温存し、
// 長期トレンド専用に JST 暦境界版を別名で追加する(SELECT のみ・DDL なし)。
// 事前条件: device_id は呼び出し前に RequireDeviceOwner で所有検証済み。$2=取得下限(期間×バッファ)。
// 事後条件: JST 暦日昇順・欠測日は行なし(handler が欠測扱いし 0 補完しない)。
func (q *Queries) ListDailySensorAggregatesJST(ctx context.Context, arg ListDailySensorAggregatesJSTParams) ([]ListDailySensorAggregatesJSTRow, error) {
	rows, err := q.db.Query(ctx, listDailySensorAggregatesJST, arg.DeviceID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailySensorAggregatesJSTRow
	for rows.Next() {
		var i ListDailySensorAggregatesJSTRow
		if err := rows.Scan(
			&i.ReadingDate,
			&i.AvgTemperature,
			&i.MaxTemperature,
			&i.MinTemperature,
			&i.AvgHumidity,
			&i.MaxHumidity,
			&i.MinHumidity,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSensorReadings = `-- name: ListLatestSensorReadings :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id = $1 AND deleted_at IS NULL
 ORDER BY recorded_at DESC
 LIMIT 10
`

// デバイス詳細の最新計測テーブル用: 最新10件を降順で取得 (期間に非連動・固定10件)
// 既存 ListRecentSensorReadings (時刻以降・昇順=24hグラフ用) とは役割が異なるため Latest で命名分離
func (q *Queries) ListLatestSensorReadings(ctx context.Context, deviceID int64) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, listLatestSensorReadings, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSensorReadings = `-- name: ListRecentSensorReadings :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at >= $2
   AND deleted_at IS NULL
 ORDER BY recorded_at ASC
`

type ListRecentSensorReadingsParams struct {
	DeviceID   int64              `json:"device_id"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

// 24時間グラフ用: 指定時刻以降の生データを昇順で取得
func (q *Queries) ListRecentSensorReadings(ctx context.Context, arg ListRecentSensorReadingsParams) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, listRecentSensorReadings, arg.DeviceID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensorReadingsInRange = `-- name: ListSensorReadingsInRange :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at BETWEEN $2 AND $3
   AND deleted_at IS NULL
 ORDER BY recorded_at ASC
`

type ListSensorReadingsInRangeParams struct {
	DeviceID     int64              `json:"device_id"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
	RecordedAt_2 pgtype.Timestamptz `json:"recorded_at_2"`
}

// CSV エクスポート / 集計帳票用: 期間内の全行を昇順で取得 (ページングなし)。
// 既存 Paginated は DESC+LIMIT、本クエリは ASC+LIMIT なし (帳票バケット/CSV 昇順出力に使う)。
func (q *Queries) ListSensorReadingsInRange(ctx context.Context, arg ListSensorReadingsInRangeParams) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, listSensorReadingsInRange, arg.DeviceID, arg.RecordedAt, arg.RecordedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensorReadingsPaginated = `-- name: ListSensorReadingsPaginated :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id   = $1
   AND recorded_at BETWEEN $2 AND $3
   AND deleted_at IS NULL
 ORDER BY recorded_at DESC
 LIMIT $4 OFFSET $5
`

type ListSensorReadingsPaginatedParams struct {
	DeviceID     int64              `json:"device_id"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
	RecordedAt_2 pgtype.Timestamptz `json:"recorded_at_2"`
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
}

// センサーデータ履歴画面のテーブル用 (期間指定 + ページング)
func (q *Queries) ListSensorReadingsPaginated(ctx context.Context, arg ListSensorReadingsPaginatedParams) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, listSensorReadingsPaginated,
		arg.DeviceID,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
