// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor_readings.sql

package repository

import (
	"context"
	"time"
)

const countSensorReadingsInRange = `-- name: CountSensorReadingsInRange :one
SELECT COUNT(*) AS total
  FROM sensor_readings
 WHERE device_id   = ?
   AND recorded_at >= ?
   AND recorded_at <= ?
   AND deleted_at IS NULL
`

type CountSensorReadingsInRangeParams struct {
	DeviceID     int64     `json:"device_id"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
}

func (q *Queries) CountSensorReadingsInRange(ctx context.Context, arg CountSensorReadingsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSensorReadingsInRange, arg.DeviceID, arg.RecordedAt, arg.RecordedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSensorReading = `-- name: CreateSensorReading :one
INSERT INTO sensor_readings (device_id, temperature, humidity, recorded_at)
VALUES (?, ?, ?, ?)
RETURNING id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at
`

type CreateSensorReadingParams struct {
	DeviceID    int64     `json:"device_id"`
	Temperature float64   `json:"temperature"`
	Humidity    float64   `json:"humidity"`
	RecordedAt  time.Time `json:"recorded_at"`
}

func (q *Queries) CreateSensorReading(ctx context.Context, arg CreateSensorReadingParams) (SensorReading, error) {
	row := q.db.QueryRowContext(ctx, createSensorReading,
		arg.DeviceID,
		arg.Temperature,
		arg.Humidity,
		arg.RecordedAt,
	)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Temperature,
		&i.Humidity,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestSensorReading = `-- name: GetLatestSensorReading :one
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id = ? AND deleted_at IS NULL
 ORDER BY recorded_at DESC
 LIMIT 1
`

func (q *Queries) GetLatestSensorReading(ctx context.Context, deviceID int64) (SensorReading, error) {
	row := q.db.QueryRowContext(ctx, getLatestSensorReading, deviceID)
	var i SensorReading
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Temperature,
		&i.Humidity,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSensorReadingsSummary = `-- name: GetSensorReadingsSummary :one
SELECT
    CAST(AVG(temperature) AS REAL) AS avg_temperature,
    CAST(MAX(temperature) AS REAL) AS max_temperature,
    CAST(MIN(temperature) AS REAL) AS min_temperature,
    CAST(AVG(humidity)    AS REAL) AS avg_humidity,
    CAST(MAX(humidity)    AS REAL) AS max_humidity,
    CAST(MIN(humidity)    AS REAL) AS min_humidity,
    COUNT(*)                       AS sample_count
  FROM sensor_readings
 WHERE device_id   = ?
   AND recorded_at >= ?
   AND recorded_at <= ?
   AND deleted_at IS NULL
 GROUP BY device_id
`

type GetSensorReadingsSummaryParams struct {
	DeviceID     int64     `json:"device_id"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
}

type GetSensorReadingsSummaryRow struct {
	AvgTemperature float64 `json:"avg_temperature"`
	MaxTemperature float64 `json:"max_temperature"`
	MinTemperature float64 `json:"min_temperature"`
	AvgHumidity    float64 `json:"avg_humidity"`
	MaxHumidity    float64 `json:"max_humidity"`
	MinHumidity    float64 `json:"min_humidity"`
	SampleCount    int64   `json:"sample_count"`
}

func (q *Queries) GetSensorReadingsSummary(ctx context.Context, arg GetSensorReadingsSummaryParams) (GetSensorReadingsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getSensorReadingsSummary, arg.DeviceID, arg.RecordedAt, arg.RecordedAt_2)
	var i GetSensorReadingsSummaryRow
	err := row.Scan(
		&i.AvgTemperature,
		&i.MaxTemperature,
		&i.MinTemperature,
		&i.AvgHumidity,
		&i.MaxHumidity,
		&i.MinHumidity,
		&i.SampleCount,
	)
	return i, err
}

const listDailySensorAggregates = `-- name: ListDailySensorAggregates :many
SELECT
    CAST(date(substr(recorded_at, 1, 19), '+9 hours') AS TEXT) AS reading_date,
    CAST(AVG(temperature) AS REAL)              AS avg_temperature,
    CAST(MAX(temperature) AS REAL)              AS max_temperature,
    CAST(MIN(temperature) AS REAL)              AS min_temperature,
    CAST(AVG(humidity)    AS REAL)              AS avg_humidity,
    CAST(MAX(humidity)    AS REAL)              AS max_humidity,
    CAST(MIN(humidity)    AS REAL)              AS min_humidity,
    COUNT(*)                                    AS sample_count
  FROM sensor_readings
 WHERE device_id   = ?
   AND recorded_at >= ?
   AND deleted_at IS NULL
 GROUP BY CAST(date(substr(recorded_at, 1, 19), '+9 hours') AS TEXT)
 ORDER BY CAST(date(substr(recorded_at, 1, 19), '+9 hours') AS TEXT) ASC
`

type ListDailySensorAggregatesParams struct {
	DeviceID   int64     `json:"device_id"`
	RecordedAt time.Time `json:"recorded_at"`
}

type ListDailySensorAggregatesRow struct {
	ReadingDate    string  `json:"reading_date"`
	AvgTemperature float64 `json:"avg_temperature"`
	MaxTemperature float64 `json:"max_temperature"`
	MinTemperature float64 `json:"min_temperature"`
	AvgHumidity    float64 `json:"avg_humidity"`
	MaxHumidity    float64 `json:"max_humidity"`
	MinHumidity    float64 `json:"min_humidity"`
	SampleCount    int64   `json:"sample_count"`
}

func (q *Queries) ListDailySensorAggregates(ctx context.Context, arg ListDailySensorAggregatesParams) ([]ListDailySensorAggregatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailySensorAggregates, arg.DeviceID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailySensorAggregatesRow
	for rows.Next() {
		var i ListDailySensorAggregatesRow
		if err := rows.Scan(
			&i.ReadingDate,
			&i.AvgTemperature,
			&i.MaxTemperature,
			&i.MinTemperature,
			&i.AvgHumidity,
			&i.MaxHumidity,
			&i.MinHumidity,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSensorReadings = `-- name: ListLatestSensorReadings :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id = ? AND deleted_at IS NULL
 ORDER BY recorded_at DESC
 LIMIT 10
`

func (q *Queries) ListLatestSensorReadings(ctx context.Context, deviceID int64) ([]SensorReading, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSensorReadings, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSensorReadings = `-- name: ListRecentSensorReadings :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id   = ?
   AND recorded_at >= ?
   AND deleted_at IS NULL
 ORDER BY recorded_at ASC
`

type ListRecentSensorReadingsParams struct {
	DeviceID   int64     `json:"device_id"`
	RecordedAt time.Time `json:"recorded_at"`
}

func (q *Queries) ListRecentSensorReadings(ctx context.Context, arg ListRecentSensorReadingsParams) ([]SensorReading, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSensorReadings, arg.DeviceID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensorReadingsPaginated = `-- name: ListSensorReadingsPaginated :many
SELECT id, device_id, temperature, humidity, recorded_at, created_at, updated_at, deleted_at FROM sensor_readings
 WHERE device_id   = ?
   AND recorded_at >= ?
   AND recorded_at <= ?
   AND deleted_at IS NULL
 ORDER BY recorded_at DESC
 LIMIT ? OFFSET ?
`

type ListSensorReadingsPaginatedParams struct {
	DeviceID     int64     `json:"device_id"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
	Limit        int64     `json:"limit"`
	Offset       int64     `json:"offset"`
}

func (q *Queries) ListSensorReadingsPaginated(ctx context.Context, arg ListSensorReadingsPaginatedParams) ([]SensorReading, error) {
	rows, err := q.db.QueryContext(ctx, listSensorReadingsPaginated,
		arg.DeviceID,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReading
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
